version: "3.7"

services:
  server:
    image: python-server:latest
    ports:
      - 9999:8000
    volumes:
      - ./temp:/app/temp

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  celery:
    restart: always
    build:
      context: .
    command: celery -A server:celery_app worker --pool=solo --loglevel=DEBUG -c 2 > log-worker.txt
    links:
      - redis
    volumes:
      - ./temp:/app/temp
    depends_on:
      - redis
      - server

networks:
  backnet:
    external: true    